version: '3.8'

services:
  # 1. Elasticsearch (The Search Engine)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: intel_elastic
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "cluster.routing.allocation.disk.watermark.low=99%"
      - "cluster.routing.allocation.disk.watermark.high=99%"
      - "cluster.routing.allocation.disk.watermark.flood_stage=99%"
      - "xpack.security.authc.api_key.enabled=true"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - intel_net
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # 2. Kibana (The Dashboard)
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: intel_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch
    networks:
      - intel_net

  # 3. Neo4j (The Graph DB)
  neo4j:
    image: neo4j:4.4
    container_name: intel_graph
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    volumes:
      - ./neo4j_data:/data
    ports:
      - "7474:7474" # HTTP UI
      - "7687:7687" # Bolt Protocol
    networks:
      - intel_net

  # 4. Redis (The Queue)
  redis:
    image: redis:alpine
    container_name: intel_queue
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - intel_net

  # 5. Tor Proxy (The Anonymity Network)
  tor-proxy:
    image: dperson/torproxy
    container_name: intel_tor
    ports:
      - "9050:9050"
      - "9051:9051"
    networks:
      - intel_net

networks:
  intel_net:
    driver: bridge